
test: tests.c data_structures.c Testy/tests_auxiliary_functions.c Testy/tests_data_structures.c
	$(CC) -o tests tests.c data_structures.c Testy/tests_auxiliary_functions.c Testy/tests_data_structures.c

